//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPrimerServicioWCF")]
public interface IPrimerServicioWCF
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicioWCF/ObtenerMensaje", ReplyAction="http://tempuri.org/IPrimerServicioWCF/ObtenerMensajeResponse")]
    string ObtenerMensaje(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicioWCF/ObtenerMensaje", ReplyAction="http://tempuri.org/IPrimerServicioWCF/ObtenerMensajeResponse")]
    System.Threading.Tasks.Task<string> ObtenerMensajeAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPrimerServicioWCFChannel : IPrimerServicioWCF, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PrimerServicioWCFClient : System.ServiceModel.ClientBase<IPrimerServicioWCF>, IPrimerServicioWCF
{
    
    public PrimerServicioWCFClient()
    {
    }
    
    public PrimerServicioWCFClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PrimerServicioWCFClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PrimerServicioWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PrimerServicioWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string ObtenerMensaje(string name)
    {
        return base.Channel.ObtenerMensaje(name);
    }
    
    public System.Threading.Tasks.Task<string> ObtenerMensajeAsync(string name)
    {
        return base.Channel.ObtenerMensajeAsync(name);
    }
}
